### PR TITLE
Concurrent logging

### PR DESCRIPTION
**Pull request by celery6**
maybe this speeds up logging idk

the concept is to split each log buffer into `n` sections, where each section will be handed off to tasks to write in. When a task uses `logInfo`, logger calculates the next free section and gives it to the task. No other task can have this section. Now multiple tasks can write to their own sections concurrently.

The downside is that most msgs do not fill the entire section, so there's a LOT of empty space. We should optimize the size of sections to be as small as possible. Possibly break up the VN log msgs into multiple msgs because that's constraining the section length requirement rn.

Other downside: buffers fill up a lot faster so it dumps to SD card more frequently. Probably not issue cuz SD card write speed is not a bottleneck.

-------------------------------------
things to test:
- run the program for a while
  - breakpoint somewhere in `log.c and verify these counters in `log.c` are all 0 
image
  - also breakpoint in `vn_handler.c` [here](https://github.com/waterloo-rocketry/cansw_processor_stm/pull/65/files#diff-dacc8aeaa93688d1ae35e8c37339d384c1f4792a133d041aff485948e8ccff92R133) to check the values of `diff1, diff2, pass1, pass2`
- open the log file from the sd card and verify every line logged is padded to the same alignment with `*` characters like the screenshot: 
image

### CODE REVIEW

**Comment by Joe-Joe-Joe-Joe** [comment]
closes #40

**Comment by Taggagii** [comment]
The `diff`s are 0 and the values are passing. If I increase the tick rate to 10000 the `diff` values are like 3-6. And also the logging is passing. However the log file is not being padded (see attached picture)
image

**Comment by Joe-Joe-Joe-Joe** [comment]
not sure what Josh means by tick rate. but this is what I got. A bunch of trailing null characters for a bunch of messages until precisely 3 seconds in when the logs shit themselves and then start padding properly
image
image

but this is what I really care about
image
Pretty sure you can't "safely" increase the tick rate (assuming you mean of freeRTOS) above 1000, at least according to the ioc file tooltip. But I can log arbitrarily sized buffers at this speed so I am happy

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
LGTM. Tested and performs better than old logging.

Does this make that other logging thing you were working on obsolete?

**Pull request merged**
